language: node_js
node_js:
  - "0.10"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd893be75c6b9908987d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   false   # default: false
